"""Generated Bash, Zsh, and Fish completion follows the live CLI tree."""
from __future__ import annotations

import hashlib
import json
import re
import subprocess
from pathlib import Path

import pytest

from scripts.llm_assist.__main__ import _build_cli_parsers, main
from scripts.llm_assist.completion import (
    SUPPORTED_SHELLS,
    completion_manifest,
    generate_completion,
)


EXPECTED_COMMAND_SURFACE_SHA256 = (
    "b4896097364f901be3db40e819637f55958c3365300e3503a97d9f1693692907"
)


def _surface_hash(manifest: dict[str, object]) -> str:
    encoded = json.dumps(
        manifest,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _parsers():
    root, session, _commands = _build_cli_parsers()
    return root, session


def test_command_surface_snapshot_detects_parser_drift() -> None:
    root, session = _parsers()
    manifest = completion_manifest(root, session)

    assert _surface_hash(manifest) == EXPECTED_COMMAND_SURFACE_SHA256


@pytest.mark.parametrize("shell", SUPPORTED_SHELLS)
def test_generation_is_deterministic_versioned_and_covers_manifest(
    shell: str,
) -> None:
    root, session = _parsers()
    manifest = completion_manifest(root, session)

    first = generate_completion(
        shell,
        root_parser=root,
        session_parser=session,
        version="9.8.7",
    )
    second = generate_completion(
        shell,
        root_parser=root,
        session_parser=session,
        version="9.8.7",
    )

    assert first == second
    assert first.endswith("\n")
    assert "Generated by yuj 9.8.7" in first
    assert EXPECTED_COMMAND_SURFACE_SHA256 in first
    for node in manifest["nodes"]:
        for command in node["subcommands"]:
            assert command["name"] in first
        for choice in node["positional_choices"]:
            assert choice in first
        for option in node["options"]:
            for name in option["names"]:
                token = name if shell != "fish" else name.lstrip("-")
                assert token in first
            for choice in option["choices"]:
                assert choice in first


def test_bash_output_is_sourceable_and_completes_options_choices_and_nested_commands(
    tmp_path: Path,
) -> None:
    root, session = _parsers()
    script = tmp_path / "yuj.bash"
    script.write_text(generate_completion(
        "bash",
        root_parser=root,
        session_parser=session,
        version="test",
    ))

    syntax = subprocess.run(
        ["bash", "-n", str(script)],
        text=True,
        capture_output=True,
        check=False,
    )
    assert syntax.returncode == 0, syntax.stderr

    def complete(words: str, index: int) -> set[str]:
        process = subprocess.run(
            [
                "bash",
                "-c",
                (
                    'source "$1"; '
                    f"COMP_WORDS=({words}); COMP_CWORD={index}; "
                    "_yuj_completion; printf '%s\\n' \"${COMPREPLY[@]}\""
                ),
                "completion-test",
                str(script),
            ],
            text=True,
            capture_output=True,
            check=False,
        )
        assert process.returncode == 0, process.stderr
        return set(process.stdout.splitlines())

    assert "--thinking" in complete("yuj config --th", 2)
    assert {"minimal", "medium"} <= complete(
        "yuj config --thinking m", 3
    )
    assert {"status", "revoke"} <= complete("yuj trust ''", 2)
    assert {"bash", "zsh", "fish"} <= complete("yuj completion ''", 2)


def test_public_completion_command_has_no_model_or_config_side_effect(
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    def forbidden(*_args, **_kwargs):
        raise AssertionError("completion must not construct a model client")

    monkeypatch.setattr("scripts.llm_assist.__main__._make_client", forbidden)

    rc = main(["completion", "fish"])

    output = capsys.readouterr().out
    assert rc == 0
    assert output.startswith("# Generated by yuj")
    assert "complete -c yuj" in output


def test_unknown_shell_fails_clearly(
    capsys: pytest.CaptureFixture[str],
) -> None:
    with pytest.raises(SystemExit) as raised:
        main(["completion", "powershell"])

    error = capsys.readouterr().err
    assert raised.value.code == 2
    assert "invalid choice" in error
    assert re.search(r"bash.*zsh.*fish", error)
