"""Tests for harness loop, tools, solver, generate pipeline, config, and end-to-end integration."""
import json
import os
import subprocess as _subprocess
import sys
import tempfile
import time
from pathlib import Path
from unittest.mock import MagicMock, patch, PropertyMock

import openai
import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from llm_solver.server.types import TurnResult, Usage, ToolCall
from llm_solver.config import Config, load_config, MODEL_MAP, _deep_merge, get_sdk_config


# ──────────────────────────────────────────────
# Helper: build a Config without loading TOML
# ──────────────────────────────────────────────

from _config_helpers import make_config  # centralized defaults — see tests/_config_helpers.py


def make_turn_result(content=None, tool_calls=None, finish_reason="stop", prompt_tokens=10):
    return TurnResult(
        content=content,
        tool_calls=tool_calls or [],
        finish_reason=finish_reason,
        usage=Usage(prompt_tokens=prompt_tokens, completion_tokens=5),
    )

_COMPACT_DEFAULTS = dict(
    recent_results_chars=30000,
    trace_reasoning_chars=150,
    min_turns=2,
    args_summary_chars=80,
)


def _make_compact(**overrides):
    from llm_solver.harness.context_strategies import CompactTranscript
    kwargs = dict(_COMPACT_DEFAULTS)
    kwargs.update(overrides)
    return CompactTranscript(**kwargs)


_SOLVER_STATE_DEFAULTS = dict(
    trace_lines=50,
    evidence_lines=30,
    inference_lines=20,
    recent_tool_results_chars=30000,
    trace_stub_chars=200,
    min_turns=2,
    suffix="Continue working. Your progress is tracked in .solver/state.json — read it to see what you've already done.",
)


def _make_solver_state(**overrides):
    from llm_solver.harness.context_strategies import SolverStateContext
    kwargs = dict(_SOLVER_STATE_DEFAULTS)
    kwargs.update(overrides)
    return SolverStateContext(**kwargs)


def _make_yuj_transcript(**overrides):
    from llm_solver.harness.context_strategies import YujTranscript
    kwargs = dict(_COMPACT_DEFAULTS)
    kwargs.update(overrides)
    return YujTranscript(**kwargs)


class TestCompactTranscript:

    def _make_assistant_msg(self, content, tool_name, tool_args, call_id="c1"):
        return {
            "role": "assistant",
            "content": content,
            "tool_calls": [{
                "id": call_id,
                "type": "function",
                "function": {
                    "name": tool_name,
                    "arguments": json.dumps(tool_args),
                },
            }],
        }

    def test_fallback_early_turns(self):
        ctx = _make_compact(original_prompt="Task X")
        ctx.add_system("sys")
        ctx.add_user("Task X")
        ctx.add_assistant(self._make_assistant_msg("thinking", "bash", {"cmd": "ls"}))
        # Only 1 turn — should return raw messages
        msgs = ctx.get_messages()
        assert len(msgs) == 3
        assert msgs[0]["role"] == "system"

    def test_compact_after_two_turns(self):
        ctx = _make_compact(original_prompt="Implement feature X")
        ctx.add_system("sys prompt")
        ctx.add_user("Implement feature X")

        # Turn 1
        ctx.add_assistant(self._make_assistant_msg("Exploring repo", "bash", {"cmd": "ls"}, "c1"))
        ctx.add_tool_result("c1", "file1.py\nfile2.py")

        # Turn 2
        ctx.add_assistant(self._make_assistant_msg("Writing code", "write", {"path": "f.py", "content": "x"}, "c2"))
        ctx.add_tool_result("c2", "OK: wrote 1 bytes to f.py")

        msgs = ctx.get_messages()
        assert len(msgs) == 2
        assert msgs[0]["role"] == "system"
        assert msgs[0]["content"] == "sys prompt"
        assert msgs[1]["role"] == "user"
        user = msgs[1]["content"]
        assert "Implement feature X" in user
        assert "Progress:" in user
        assert "Exploring repo" in user
        assert "Writing code" in user
        assert "bash(" in user
        assert "write(" in user

    def test_outcome_classification(self):
        from llm_solver.harness.context_strategies.compact_transcript import _classify_outcome
        # Content-blind classification: only harness-generated markers count.
        assert _classify_outcome("file1.py\nfile2.py") == "OK"
        assert _classify_outcome("OK: wrote 10 bytes") == "OK"
        # ERROR: wrapper is harness-generated (tools.py wraps exceptions).
        assert _classify_outcome("ERROR: file not found: foo.py") == "FAIL"
        # Tracebacks are task content — harness does NOT parse them.
        assert _classify_outcome(
            "Traceback (most recent call last):\n  File...\nNameError: name 'x'"
        ) == "OK"
        # [exit code: N] is harness-generated by bash() when N != 0.
        assert _classify_outcome("output\n[exit code: 1]") == "FAIL"
        assert _classify_outcome("output\n[exit code: 0]") == "OK"

    def test_recent_results_unbounded_when_small(self):
        """With small results, the char-budget window keeps every turn.
        Previously the deque was maxlen=3 and older results were dropped
        even when they were tiny, which starved the model of recent code
        reads. Now small results accumulate and the model sees them all.
        """
        ctx = _make_compact(original_prompt="Task")
        ctx.add_system("sys")
        ctx.add_user("Task")

        for i in range(5):
            ctx.add_assistant(self._make_assistant_msg(f"step {i}", "bash", {"cmd": f"echo {i}"}, f"c{i}"))
            ctx.add_tool_result(f"c{i}", f"result_{i}")

        msgs = ctx.get_messages()
        user = msgs[1]["content"]
        # Every result is present — tiny results fit under the budget.
        for i in range(5):
            assert f"result_{i}" in user

    def test_recent_results_char_budget_evicts_oldest(self):
        """When the total char budget overflows, oldest results evict. The
        rolling window trims both the render AND the underlying deque so
        memory stays bounded across long sessions.
        """
        # 10000-char budget so 3 x 5000-char results overflow and one evicts.
        ctx = _make_compact(original_prompt="Task", recent_results_chars=10000)
        ctx.add_system("sys")
        ctx.add_user("Task")

        for i, tag in enumerate(["A", "B", "C"]):
            ctx.add_assistant(self._make_assistant_msg(f"step {i}", "bash", {"cmd": f"echo {i}"}, f"c{i}"))
            ctx.add_tool_result(f"c{i}", tag * 5000)

        msgs = ctx.get_messages()
        user = msgs[1]["content"]
        assert "C" * 100 in user  # newest
        assert "B" * 100 in user  # fits
        assert "A" * 5000 not in user  # evicted
        assert len(ctx._recent_results) < 3

    def test_progress_log_has_all_turns(self):
        ctx = _make_compact(original_prompt="Task")
        ctx.add_system("sys")
        ctx.add_user("Task")

        for i in range(10):
            ctx.add_assistant(self._make_assistant_msg(f"action {i}", "bash", {"cmd": f"cmd{i}"}, f"c{i}"))
            ctx.add_tool_result(f"c{i}", f"ok_{i}")

        msgs = ctx.get_messages()
        user = msgs[1]["content"]
        # All 10 turns in progress log
        for i in range(10):
            assert f"action {i}" in user

    def test_empty_reasoning_handled(self):
        ctx = _make_compact(original_prompt="Task")
        ctx.add_system("sys")
        ctx.add_user("Task")

        # Assistant with no content (just tool calls)
        msg = self._make_assistant_msg(None, "bash", {"cmd": "ls"}, "c1")
        msg["content"] = None
        ctx.add_assistant(msg)
        ctx.add_tool_result("c1", "files")

        ctx.add_assistant(self._make_assistant_msg("second", "bash", {"cmd": "pwd"}, "c2"))
        ctx.add_tool_result("c2", "/tmp")

        msgs = ctx.get_messages()
        user = msgs[1]["content"]
        assert "bash(" in user  # structural still present even without reasoning

    def test_estimate_tokens(self):
        ctx = _make_compact(original_prompt="Task")
        ctx.add_system("sys")
        ctx.add_user("Task")
        ctx.add_assistant(self._make_assistant_msg("a", "bash", {"cmd": "ls"}, "c1"))
        ctx.add_tool_result("c1", "ok")
        ctx.add_assistant(self._make_assistant_msg("b", "bash", {"cmd": "pwd"}, "c2"))
        ctx.add_tool_result("c2", "ok")
        tokens = ctx.estimate_tokens()
        assert isinstance(tokens, int)
        assert tokens > 0

    def test_multi_tool_calls(self):
        ctx = _make_compact(original_prompt="Task")
        ctx.add_system("sys")
        ctx.add_user("Task")

        # Assistant with two tool calls in one turn
        msg = {
            "role": "assistant",
            "content": "Reading two files",
            "tool_calls": [
                {"id": "c1", "type": "function", "function": {"name": "read", "arguments": '{"path": "a.py"}'}},
                {"id": "c2", "type": "function", "function": {"name": "read", "arguments": '{"path": "b.py"}'}},
            ],
        }
        ctx.add_assistant(msg)
        ctx.add_tool_result("c1", "contents of a")
        ctx.add_tool_result("c2", "contents of b")

        # Second turn to trigger compact mode
        ctx.add_assistant(self._make_assistant_msg("next step", "bash", {"cmd": "ls"}, "c3"))
        ctx.add_tool_result("c3", "files")

        msgs = ctx.get_messages()
        user = msgs[1]["content"]
        # Both tool calls should appear in progress
        assert "read(" in user
        assert "Reading two files" in user
        # Second tool call of same turn also recorded (without reasoning)
        assert user.count("read(") >= 2


# ──────────────────────────────────────────────
# YujTranscript
# ──────────────────────────────────────────────

class TestYujTranscript:

    def _make_assistant_msg(self, content, tool_name, tool_args, call_id="c1"):
        return {
            "role": "assistant",
            "content": content,
            "tool_calls": [{
                "id": call_id,
                "type": "function",
                "function": {
                    "name": tool_name,
                    "arguments": json.dumps(tool_args),
                },
            }],
        }

    def test_yuj_sections_present(self):
        ctx = _make_yuj_transcript(original_prompt="Fix the bug")
        ctx.add_system("sys")
        ctx.add_user("Fix the bug")

        ctx.add_assistant(self._make_assistant_msg("Reading code", "read", {"path": "a.py"}, "c1"))
        ctx.add_tool_result("c1", "def foo(): pass")

        # Non-zero exit code is harness-generated — classify_outcome will mark FAIL.
        ctx.add_assistant(self._make_assistant_msg("Running verification", "bash", {"cmd": "./verify"}, "c2"))
        ctx.add_tool_result("c2", "some output\n[exit code: 1]")

        msgs = ctx.get_messages()
        assert len(msgs) == 2
        user = msgs[1]["content"]

        # Protocol sections present
        assert "=== Trace ===" in user
        assert "=== Evidence (unresolved) ===" in user
        assert "=== Gate (blocking) ===" in user
        assert "=== State ===" in user

        # Trace has all actions
        assert "Reading code" in user
        assert "Running verification" in user

        # Evidence has only failures (content-blind: exit code was non-zero).
        assert "FAIL" in user

        # State has turn info
        assert "Turn:" in user

    def test_no_evidence_when_all_pass(self):
        ctx = _make_yuj_transcript(original_prompt="Task")
        ctx.add_system("sys")
        ctx.add_user("Task")

        ctx.add_assistant(self._make_assistant_msg("step 1", "bash", {"cmd": "ls"}, "c1"))
        ctx.add_tool_result("c1", "files")

        ctx.add_assistant(self._make_assistant_msg("step 2", "bash", {"cmd": "pwd"}, "c2"))
        ctx.add_tool_result("c2", "/tmp")

        msgs = ctx.get_messages()
        user = msgs[1]["content"]

        assert "=== Trace ===" in user
        assert "=== Evidence" not in user  # no failures
        assert "=== Gate" not in user

    def test_inherits_compact_behavior(self):
        ctx = _make_yuj_transcript(original_prompt="Task")
        ctx.add_system("sys")
        ctx.add_user("Task")

        # Fallback on turn 0
        ctx.add_assistant(self._make_assistant_msg("a", "bash", {"cmd": "ls"}, "c1"))
        msgs = ctx.get_messages()
        assert len(msgs) == 3  # raw messages, not compact

        # After turn 2, compact
        ctx.add_tool_result("c1", "ok")
        ctx.add_assistant(self._make_assistant_msg("b", "bash", {"cmd": "pwd"}, "c2"))
        ctx.add_tool_result("c2", "ok")

        msgs = ctx.get_messages()
        assert len(msgs) == 2  # compact mode


# ──────────────────────────────────────────────
# 16. Turn-level error detection (#18)
# ──────────────────────────────────────────────

class TestErrorDetection:

    def test_nudge_after_consecutive_errors(self):
        """Consecutive errors queue a nudge for the next model request."""
        from llm_solver.harness.loop import Session
        threshold = 3
        cfg = make_config(max_turns=threshold + 2, duplicate_abort=20,
                          error_nudge_threshold=threshold)
        client = MagicMock()

        call_count = [0]
        def chat_fn(*args, **kwargs):
            call_count[0] += 1
            if call_count[0] > threshold:
                return make_turn_result(content="done", finish_reason="stop")
            tc = [ToolCall(id=f"c{call_count[0]}", name="edit",
                          arguments={"path": f"f{call_count[0]}.py", "old_str": "a", "new_str": "b"})]
            return make_turn_result(tool_calls=tc, finish_reason="tool_calls")

        client.chat.side_effect = chat_fn
        client.build_assistant_message.return_value = {"role": "assistant", "content": None}

        tool_results = []
        with patch("llm_solver.harness.loop.dispatch", return_value="ERROR: old_str not found"):
            session = Session(cfg, client, "sys", "prompt", "/tmp")
            orig_add = session.context.add_tool_result
            def capture(cid, result, **kwargs):
                tool_results.append(result)
                return orig_add(cid, result, **kwargs)
            session.context.add_tool_result = capture
            session.run()

        assert all(result == "ERROR: old_str not found" for result in tool_results)
        request_text = "\n".join(
            str(message.get("content") or "")
            for call in client.chat.call_args_list
            for message in call.args[0]
        )
        assert "[harness:" in request_text
        assert f"{threshold} consecutive" in request_text

    def test_error_counter_resets_on_success(self):
        """Successful dispatch resets consecutive error counter — no nudge emitted."""
        from llm_solver.harness.loop import Session
        cfg = make_config(max_turns=10, duplicate_abort=20, error_nudge_threshold=3)
        client = MagicMock()

        call_count = [0]
        def chat_fn(*args, **kwargs):
            call_count[0] += 1
            if call_count[0] > 4:
                return make_turn_result(content="done", finish_reason="stop")
            tc = [ToolCall(id=f"c{call_count[0]}", name="bash",
                          arguments={"cmd": f"cmd{call_count[0]}"})]
            return make_turn_result(tool_calls=tc, finish_reason="tool_calls")

        client.chat.side_effect = chat_fn
        client.build_assistant_message.return_value = {"role": "assistant", "content": None}

        # Alternate error/success — never reaches threshold
        dispatch_returns = iter(["ERROR: fail", "ok", "ERROR: fail", "ok"])
        tool_results = []
        with patch("llm_solver.harness.loop.dispatch", side_effect=dispatch_returns):
            session = Session(cfg, client, "sys", "prompt", "/tmp")
            orig_add = session.context.add_tool_result
            def capture(cid, result, **kwargs):
                tool_results.append(result)
                return orig_add(cid, result, **kwargs)
            session.context.add_tool_result = capture
            session.run()

        nudge_results = [r for r in tool_results if "[harness:" in r]
        assert len(nudge_results) == 0, f"Unexpected nudge: {nudge_results}"

    def test_error_detection_logs_events(self):
        """Error events are logged at INFO level."""
        from llm_solver.harness.loop import Session
        cfg = make_config(max_turns=3, duplicate_abort=20)
        client = MagicMock()

        call_count = [0]
        def chat_fn(*args, **kwargs):
            call_count[0] += 1
            if call_count[0] > 1:
                return make_turn_result(content="done", finish_reason="stop")
            tc = [ToolCall(id="c1", name="bash", arguments={"cmd": "bad"})]
            return make_turn_result(tool_calls=tc, finish_reason="tool_calls")

        client.chat.side_effect = chat_fn
        client.build_assistant_message.return_value = {"role": "assistant", "content": None}

        import logging
        with patch("llm_solver.harness.loop.dispatch", return_value="ERROR: fail"):
            session = Session(cfg, client, "sys", "prompt", "/tmp")
            with patch("llm_solver.harness.loop.log") as mock_log:
                session.run()

        # At least one INFO log about tool error
        info_calls = [str(c) for c in mock_log.info.call_args_list]
        assert any("error" in c.lower() or "ERROR" in c for c in info_calls)


class TestPostMutationVerificationNudge:

    def test_nudge_is_one_shot_user_turn_after_source_mutation(self, tmp_path):
        from llm_solver.harness.loop import Session

        cfg = make_config(
            max_turns=4,
            duplicate_abort=20,
            post_mutation_verification_gate_after=3,
        )
        client = MagicMock()
        call_count = [0]

        def chat_fn(*args, **kwargs):
            call_count[0] += 1
            if call_count[0] > 2:
                return make_turn_result(content="done", finish_reason="stop")
            tc = [ToolCall(
                id=f"c{call_count[0]}",
                name="edit",
                arguments={
                    "path": f"src/core_{call_count[0]}.py",
                    "old_str": "before",
                    "new_str": "after",
                },
            )]
            return make_turn_result(tool_calls=tc, finish_reason="tool_calls")

        client.chat.side_effect = chat_fn
        client.build_assistant_message.return_value = {
            "role": "assistant", "content": None,
        }

        tool_results = []
        trace_path = tmp_path / ".trace.jsonl"
        with trace_path.open("a") as trace_file, patch(
            "llm_solver.harness.loop.dispatch", return_value="OK: edit applied"
        ):
            session = Session(
                cfg,
                client,
                "sys",
                "prompt",
                str(tmp_path),
                trace_file=trace_file,
                trace_path=trace_path,
                session_number=1,
            )
            original_add = session.context.add_tool_result

            def capture(tool_call_id, result, **kwargs):
                tool_results.append(result)
                return original_add(tool_call_id, result, **kwargs)

            session.context.add_tool_result = capture
            session.run()

        advice = cfg.post_mutation_verification_nudge
        second_request = client.chat.call_args_list[1].args[0]
        assert any(
            message.get("role") == "user"
            and advice in str(message.get("content") or "")
            for message in second_request
        )
        assert all(advice not in result for result in tool_results)

        events = [
            json.loads(line)
            for line in trace_path.read_text().splitlines()
            if line.strip()
        ]
        injections = [
            event
            for event in events
            if event.get("event") == "user_turn_injection"
            and event.get("mechanism") == "post_mutation_verification_nudge"
        ]
        assert len(injections) == 1
        assert injections[0]["tool_call_id"] == "c1"

    def test_custom_shell_streak_is_blocked_until_formal_runner(self, tmp_path):
        from llm_solver.harness.loop import Session

        cfg = make_config(
            max_turns=7,
            duplicate_abort=20,
            post_mutation_verification_gate_after=2,
        )
        client = MagicMock()
        calls = [
            ToolCall(
                id="edit-1",
                name="edit",
                arguments={
                    "path": "src/core.py",
                    "old_str": "before",
                    "new_str": "after",
                },
            ),
            ToolCall(
                id="custom-1",
                name="bash",
                arguments={"cmd": "python -c 'print(1)'"},
            ),
            ToolCall(
                id="custom-2",
                name="bash",
                arguments={"cmd": "python -c 'print(2)'"},
            ),
            ToolCall(
                id="custom-blocked",
                name="bash",
                arguments={"cmd": "python -c 'print(3)'"},
            ),
            ToolCall(
                id="formal-1",
                name="bash",
                arguments={
                    "cmd": "python -m pytest tests/test_component.py -q"
                },
            ),
            ToolCall(id="done-1", name="done", arguments={}),
        ]
        turn = [0]

        def chat_fn(*args, **kwargs):
            index = turn[0]
            turn[0] += 1
            return make_turn_result(
                tool_calls=[calls[index]],
                finish_reason="tool_calls",
            )

        client.chat.side_effect = chat_fn
        client.build_assistant_message.return_value = {
            "role": "assistant",
            "content": None,
        }
        executed: list[str] = []

        def dispatch_fn(name, arguments, **kwargs):
            executed.append(arguments.get("cmd", name))
            if name == "edit":
                return "OK: edit applied"
            if "pytest" in arguments.get("cmd", ""):
                return "14 passed in 0.5s"
            return "ok"

        with patch(
            "llm_solver.harness.loop.dispatch", side_effect=dispatch_fn
        ):
            result = Session(
                cfg,
                client,
                "sys",
                "prompt",
                str(tmp_path),
                session_number=1,
            ).run()

        assert result.done is True
        assert "python -c 'print(3)'" not in executed
        assert any("pytest tests/test_component.py" in cmd for cmd in executed)

    def test_implicit_done_waits_for_formal_runner(self, tmp_path):
        from llm_solver.harness.loop import Session

        cfg = make_config(
            max_turns=4,
            duplicate_abort=20,
            post_mutation_verification_gate_after=2,
        )
        client = MagicMock()
        responses = [
            make_turn_result(
                tool_calls=[ToolCall(
                    id="edit-1",
                    name="edit",
                    arguments={
                        "path": "src/core.py",
                        "old_str": "before",
                        "new_str": "after",
                    },
                )],
                finish_reason="tool_calls",
            ),
            make_turn_result(content="done", finish_reason="stop"),
            make_turn_result(
                tool_calls=[ToolCall(
                    id="formal-1",
                    name="bash",
                    arguments={
                        "cmd": "python -m pytest tests/test_component.py -q"
                    },
                )],
                finish_reason="tool_calls",
            ),
            make_turn_result(content="done", finish_reason="stop"),
        ]
        client.chat.side_effect = responses
        client.build_assistant_message.return_value = {
            "role": "assistant",
            "content": None,
        }
        executed: list[str] = []

        def dispatch_fn(name, arguments, **kwargs):
            executed.append(arguments.get("cmd", name))
            if name == "edit":
                return "OK: edit applied"
            return "14 passed in 0.5s"

        with patch(
            "llm_solver.harness.loop.dispatch", side_effect=dispatch_fn
        ):
            result = Session(
                cfg,
                client,
                "sys",
                "prompt",
                str(tmp_path),
                session_number=1,
            ).run()

        assert result.done is True
        assert client.chat.call_count == 4
        assert any("pytest tests/test_component.py" in cmd for cmd in executed)
